import type { Supplement } from "@/types/supplements";

export const SUPPLEMENTS: Supplement[] = [
  {
    id: "vitamin_d",
    name: "Vitamin D3",
    category: "Vitamin",
    bestFor: ["bone_health", "immune", "general_wellness"],
    evidenceLevel: "Strong",
    safetyLevel: "Low",
    contraindications: ["Hypercalcemia", "Sarcoidosis", "Kidney disease (without monitoring)"],
    medicationInteractions: ["Thiazide diuretics", "Digoxin", "Some steroids"],
    recommendedOnlyIf: ["Low sun exposure", "Northern latitude", "Darker skin", "Older adult", "Limited dietary intake"],
    foodFirstAdvice: "Fatty fish, egg yolks, fortified dairy/plant milks, and ~10–20 min of midday sun (when safe) can support vitamin D status.",
    typicalUseCase: "Common shortfall, especially in winter, indoors, or with limited sun exposure.",
    whatToLookFor: ["D3 (cholecalciferol)", "Third-party tested (USP/NSF)", "Conservative daily dose unless tested low"],
    avoidIf: ["You take high-dose vitamin D already", "You have hypercalcemia"],
    resultCopy:
      "Vitamin D supports bone, immune, and muscle function. Many adults fall short—consider testing 25(OH)D and discussing a sensible daily dose with your clinician.",
    citationsPlaceholder: ["NIH ODS Vitamin D", "Endocrine Society guidance"],
  },
  {
    id: "b12",
    name: "Vitamin B12 (Methylcobalamin/Cyanocobalamin)",
    category: "Vitamin",
    bestFor: ["energy", "general_wellness", "focus"],
    evidenceLevel: "Strong",
    safetyLevel: "Low",
    contraindications: ["Leber's disease"],
    medicationInteractions: ["Metformin (may lower B12)", "PPIs/H2 blockers"],
    recommendedOnlyIf: ["Vegan/vegetarian diet", "Age 50+", "On metformin or acid-reducers", "History of anemia"],
    foodFirstAdvice: "Animal foods, dairy, eggs, and B12-fortified plant foods/nutritional yeast are reliable sources.",
    typicalUseCase: "Vegans, older adults, and those on certain medications are at higher risk for B12 shortfall.",
    whatToLookFor: ["Methyl- or cyanocobalamin", "Third-party tested", "Modest daily or weekly dose"],
    avoidIf: ["You already eat ample B12-rich foods and have normal labs"],
    resultCopy:
      "B12 supports nerves, blood cells, and energy metabolism. Plant-based eaters and older adults often benefit—ask your clinician about testing if symptoms persist.",
    citationsPlaceholder: ["NIH ODS B12"],
  },
  {
    id: "omega3",
    name: "Omega-3 (EPA/DHA)",
    category: "Fatty acid",
    bestFor: ["general_wellness", "muscle_recovery", "focus"],
    evidenceLevel: "Moderate",
    safetyLevel: "Low",
    contraindications: ["Fish/shellfish allergy (unless algal)"],
    medicationInteractions: ["Blood thinners (increased bleeding risk at high doses)"],
    recommendedOnlyIf: ["Low oily-fish intake (<2 servings/week)", "Vegan (use algal EPA/DHA)"],
    foodFirstAdvice: "Two servings/week of low-mercury oily fish (salmon, sardines, mackerel) usually covers needs.",
    typicalUseCase: "People who rarely eat oily fish.",
    whatToLookFor: ["EPA+DHA amount on label (not just 'fish oil')", "IFOS or third-party tested for purity", "Algal oil for vegans"],
    avoidIf: ["You take blood thinners without clinician guidance", "You already eat ample oily fish"],
    resultCopy:
      "EPA/DHA omega-3s support heart, brain, and recovery. If you rarely eat oily fish, a quality-tested fish or algal oil is a sensible option.",
    citationsPlaceholder: ["NIH ODS Omega-3"],
  },
  {
    id: "magnesium",
    name: "Magnesium (Glycinate/Citrate)",
    category: "Mineral",
    bestFor: ["sleep", "muscle_recovery", "general_wellness"],
    evidenceLevel: "Moderate",
    safetyLevel: "Low",
    contraindications: ["Severe kidney disease"],
    medicationInteractions: ["Certain antibiotics", "Bisphosphonates", "Some blood pressure meds"],
    recommendedOnlyIf: ["Poor sleep", "Frequent training", "Low intake of greens/legumes/nuts"],
    foodFirstAdvice: "Leafy greens, nuts/seeds, legumes, whole grains, and dark chocolate are rich sources.",
    typicalUseCase: "Active people, poor sleepers, low whole-food intake.",
    whatToLookFor: ["Glycinate or citrate forms", "Avoid oxide (poor absorption)", "Third-party tested"],
    avoidIf: ["You have advanced kidney disease without clinician oversight"],
    resultCopy:
      "Magnesium supports sleep, muscle, and nervous system function. A modest evening dose of glycinate or citrate is a common, well-tolerated choice.",
    citationsPlaceholder: ["NIH ODS Magnesium"],
  },
  {
    id: "creatine",
    name: "Creatine Monohydrate",
    category: "Performance",
    bestFor: ["muscle_recovery", "endurance", "focus"],
    evidenceLevel: "Strong",
    safetyLevel: "Low",
    contraindications: ["Significant kidney disease"],
    medicationInteractions: ["Nephrotoxic medications (discuss with clinician)"],
    recommendedOnlyIf: ["Resistance training", "Goal: strength/recovery/cognition"],
    foodFirstAdvice: "Red meat and fish contain creatine, but doses are small vs. typical supplemental intake.",
    typicalUseCase: "Strength, power, recovery, and cognitive support in active adults.",
    whatToLookFor: ["Creatine monohydrate (not 'blends')", "Creapure or third-party tested", "Unflavored powder is cheapest"],
    avoidIf: ["You have kidney disease without clinician guidance"],
    resultCopy:
      "Creatine monohydrate is one of the most studied and reliable performance supplements. A consistent daily dose supports strength, recovery, and possibly cognition.",
    citationsPlaceholder: ["ISSN Position Stand on Creatine"],
  },
  {
    id: "protein",
    name: "Protein Powder (Whey/Plant)",
    category: "Macronutrient",
    bestFor: ["muscle_recovery", "weight_management", "general_wellness"],
    evidenceLevel: "Strong",
    safetyLevel: "Low",
    contraindications: ["Milk allergy (whey)", "Severe kidney disease"],
    medicationInteractions: [],
    recommendedOnlyIf: ["Difficulty hitting daily protein from food", "High training load", "Calorie deficit"],
    foodFirstAdvice: "Whole-food protein (eggs, dairy, fish, poultry, tofu/tempeh, legumes) should come first.",
    typicalUseCase: "Convenient way to top up daily protein intake.",
    whatToLookFor: ["Third-party tested (Informed Sport/NSF)", "Short ingredient list", "Avoid proprietary 'amino spiking' blends"],
    avoidIf: ["You already meet protein needs from food"],
    resultCopy:
      "A quality-tested protein powder is a convenient way to support recovery and satiety—especially during heavy training or a calorie deficit.",
    citationsPlaceholder: ["ISSN Protein Position Stand"],
  },
  {
    id: "iron",
    name: "Iron",
    category: "Mineral",
    bestFor: ["energy"],
    evidenceLevel: "Situational",
    safetyLevel: "High caution",
    contraindications: ["Hemochromatosis", "Iron overload", "No evidence of deficiency"],
    medicationInteractions: ["Levothyroxine", "Some antibiotics", "PPIs (reduce absorption)"],
    recommendedOnlyIf: ["Confirmed low iron/ferritin via labs", "Heavy menstrual losses", "Pregnancy under clinician care"],
    foodFirstAdvice: "Lean red meat, poultry, fish, legumes, tofu, and fortified grains—pair plant iron with vitamin C.",
    typicalUseCase: "Only for documented deficiency or clinician-directed use.",
    whatToLookFor: ["Form and dose chosen with a clinician", "Third-party tested"],
    avoidIf: ["You do not have a confirmed deficiency", "You have hemochromatosis or iron overload"],
    resultCopy:
      "Iron should not be supplemented casually. We do not recommend starting iron without lab testing (ferritin/CBC) and clinician guidance—excess iron can be harmful.",
    citationsPlaceholder: ["NIH ODS Iron"],
  },
  {
    id: "calcium",
    name: "Calcium",
    category: "Mineral",
    bestFor: ["bone_health"],
    evidenceLevel: "Moderate",
    safetyLevel: "Moderate",
    contraindications: ["History of kidney stones (some types)", "Hypercalcemia"],
    medicationInteractions: ["Thyroid meds", "Some antibiotics", "Certain blood pressure meds"],
    recommendedOnlyIf: ["Low dairy/calcium-rich food intake", "Postmenopausal at risk", "Vegan with low fortified intake"],
    foodFirstAdvice: "Dairy, fortified plant milks, tofu set with calcium, leafy greens, sardines with bones.",
    typicalUseCase: "Fill the gap if dietary intake is consistently low.",
    whatToLookFor: ["Citrate or carbonate (with food)", "Modest dose to fill the gap, not megadose", "Third-party tested"],
    avoidIf: ["You already meet calcium needs from food", "You have a history of certain kidney stones"],
    resultCopy:
      "Aim for food-first calcium. Use a modest supplement only to fill a real gap—high-dose calcium isn't better and may carry risks.",
    citationsPlaceholder: ["NIH ODS Calcium"],
  },
  {
    id: "prenatal",
    name: "Prenatal / Folate",
    category: "Vitamin",
    bestFor: ["general_wellness"],
    evidenceLevel: "Strong",
    safetyLevel: "Moderate",
    contraindications: ["Not appropriate for general population"],
    medicationInteractions: ["Some seizure medications", "Methotrexate"],
    recommendedOnlyIf: ["Pregnant", "Trying to conceive", "Breastfeeding (per clinician)"],
    foodFirstAdvice: "Leafy greens, legumes, citrus, and fortified grains contribute folate; whole-diet quality matters most.",
    typicalUseCase: "Preconception and pregnancy—coordinated with prenatal care.",
    whatToLookFor: ["Folate/folic acid at guideline levels", "Iron content reviewed with clinician", "Third-party tested"],
    avoidIf: ["You are not pregnant, trying, or breastfeeding"],
    resultCopy:
      "If you're pregnant, breastfeeding, or trying to conceive, a prenatal with folate is standard practice—choose it together with your obstetric clinician.",
    citationsPlaceholder: ["ACOG guidance", "CDC folate guidance"],
  },
  {
    id: "electrolytes",
    name: "Electrolytes (Sodium/Potassium/Magnesium)",
    category: "Hydration",
    bestFor: ["endurance", "energy"],
    evidenceLevel: "Moderate",
    safetyLevel: "Low",
    contraindications: ["Salt-sensitive hypertension (sodium load)", "Kidney disease"],
    medicationInteractions: ["Potassium-sparing diuretics", "ACE inhibitors/ARBs (potassium)"],
    recommendedOnlyIf: ["Long/intense training", "Hot climate", "Heavy sweating"],
    foodFirstAdvice: "Balanced meals with sodium, potassium-rich produce, and adequate water cover most needs.",
    typicalUseCase: "Endurance athletes, sweat-heavy training, hot environments.",
    whatToLookFor: ["Transparent sodium/potassium amounts", "Low/no sugar if preferred", "Third-party tested"],
    avoidIf: ["You have blood pressure or kidney issues without clinician input"],
    resultCopy:
      "Electrolyte drinks can help during long, sweaty, or hot training sessions. Choose products with transparent labels and amounts that match your needs.",
    citationsPlaceholder: ["ACSM hydration guidance"],
  },
  {
    id: "fiber",
    name: "Fiber (Psyllium)",
    category: "Fiber",
    bestFor: ["general_wellness", "weight_management"],
    evidenceLevel: "Strong",
    safetyLevel: "Low",
    contraindications: ["Bowel obstruction", "Swallowing difficulty"],
    medicationInteractions: ["May reduce absorption of some meds—separate by 2+ hours"],
    recommendedOnlyIf: ["Low fruit/veg/whole-grain intake", "Constipation"],
    foodFirstAdvice: "Fruits, vegetables, legumes, oats, and whole grains should be the foundation.",
    typicalUseCase: "Top-up fiber when whole-food intake is low.",
    whatToLookFor: ["Pure psyllium husk", "No added stimulant laxatives", "Take with plenty of water"],
    avoidIf: ["You have a GI obstruction or trouble swallowing"],
    resultCopy:
      "Most people fall short on fiber. Build meals around plants first; psyllium is a simple, evidence-supported way to fill a gap.",
    citationsPlaceholder: ["Academy of Nutrition & Dietetics"],
  },
  {
    id: "probiotic",
    name: "Probiotic",
    category: "Gut",
    bestFor: ["general_wellness", "immune"],
    evidenceLevel: "Limited",
    safetyLevel: "Low",
    contraindications: ["Severely immunocompromised (clinician guidance)"],
    medicationInteractions: ["Antibiotics—separate timing if used"],
    recommendedOnlyIf: ["After a course of antibiotics (short term)", "Specific strain-condition match"],
    foodFirstAdvice: "Yogurt, kefir, kimchi, sauerkraut, miso, and fiber-rich plants for the microbiome.",
    typicalUseCase: "Targeted, short-term use; benefits are strain-specific.",
    whatToLookFor: ["Specific strain names and CFU counts", "Studied indication match", "Third-party tested"],
    avoidIf: ["You are severely immunocompromised without clinician input"],
    resultCopy:
      "Probiotic evidence is strain-specific, not generic. If you want to try one, pick a strain studied for your situation and keep expectations realistic.",
    citationsPlaceholder: ["AGA probiotic guideline"],
  },
  {
    id: "zinc",
    name: "Zinc",
    category: "Mineral",
    bestFor: ["immune"],
    evidenceLevel: "Limited",
    safetyLevel: "Moderate",
    contraindications: ["Long-term high doses can cause copper deficiency"],
    medicationInteractions: ["Some antibiotics", "Penicillamine"],
    recommendedOnlyIf: ["Short-term during early cold symptoms", "Documented low intake/deficiency"],
    foodFirstAdvice: "Meat, shellfish, legumes, seeds, and whole grains supply zinc.",
    typicalUseCase: "Short-term, modest dose—not chronic high-dose use.",
    whatToLookFor: ["Modest dose (well under upper limit)", "Avoid intranasal zinc", "Third-party tested"],
    avoidIf: ["You're already taking a multivitamin with adequate zinc"],
    resultCopy:
      "Short-term, modest zinc may shorten cold symptoms for some people. Avoid chronic high doses—they can backfire on copper status.",
    citationsPlaceholder: ["NIH ODS Zinc"],
  },
  {
    id: "vitamin_c",
    name: "Vitamin C",
    category: "Vitamin",
    bestFor: ["immune", "general_wellness"],
    evidenceLevel: "Limited",
    safetyLevel: "Low",
    contraindications: ["History of oxalate kidney stones (high doses)"],
    medicationInteractions: ["Some chemo drugs (discuss with oncology)"],
    recommendedOnlyIf: ["Low fruit/vegetable intake", "Smokers (higher needs)"],
    foodFirstAdvice: "Citrus, berries, kiwi, peppers, broccoli, and tomatoes are easy daily sources.",
    typicalUseCase: "Fill a gap when produce intake is low.",
    whatToLookFor: ["Modest daily dose", "Third-party tested"],
    avoidIf: ["You already eat plenty of fruits and vegetables"],
    resultCopy:
      "Most people can get enough vitamin C from food. A modest supplement is a reasonable backup when produce intake is low.",
    citationsPlaceholder: ["NIH ODS Vitamin C"],
  },
  {
    id: "melatonin",
    name: "Melatonin (Low Dose)",
    category: "Sleep",
    bestFor: ["sleep"],
    evidenceLevel: "Moderate",
    safetyLevel: "Moderate",
    contraindications: ["Pregnancy/breastfeeding", "Autoimmune conditions (discuss)", "Children (clinician only)"],
    medicationInteractions: ["Sedatives", "Blood thinners", "Immunosuppressants", "Some blood pressure meds"],
    recommendedOnlyIf: ["Jet lag", "Short-term circadian shift", "Shift work (clinician guidance)"],
    foodFirstAdvice: "Prioritize sleep hygiene: consistent schedule, dark/cool room, limited late caffeine/alcohol, daytime light exposure.",
    typicalUseCase: "Short-term circadian support, not nightly sedation.",
    whatToLookFor: ["Low dose (0.3–1 mg often sufficient)", "Third-party tested (dose accuracy is a known issue)"],
    avoidIf: ["Pregnant/breastfeeding", "Under 18 without clinician guidance"],
    resultCopy:
      "For occasional jet lag or schedule shifts, a low-dose, third-party-tested melatonin can help. Fix sleep habits first—it isn't a long-term sedative.",
    citationsPlaceholder: ["AASM melatonin guidance"],
  },
];

export const RED_FLAG_INGREDIENTS = [
  "St. John's wort",
  "High-dose vitamin A (retinol)",
  "High-dose vitamin D (megadose)",
  "High-dose zinc (long-term)",
  "Kava",
  "Weight-loss / fat-burner blends",
  "Testosterone boosters",
  '"Proprietary blends" without disclosed amounts',
  'Products claiming to "treat", "cure", or "be FDA approved"',
];
